In [2]:
# 코드 환경 셋팅

import tensorflow as tf
import numpy as np
import pprint           # print를 조금 더 이쁘게 나오도록 하는 라이브러리

pp = pprint.PrettyPrinter(indent=4)
print(tf.__version__)

2.2.0


In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)

print(t.ndim)
print(t.shape)
print(t[0], t[1], t[-1])
print(t[2:5], t[4: -1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [ ]:
t = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
pp.pprint(t)

print(t.ndim)
print(t.shape)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])
2
(4, 3)


In [ ]:
t = tf.constant([1, 2, 3, 4])
tf.shape(t).eval()                # eval()은 tensorflow 1.x 버전대의 메소드 / 2.x 버전은 numpy()

NotImplementedError: ignored

In [ ]:
t = tf.constant([1, 2, 3, 4])
tf.shape(t).numpy()

array([4], dtype=int32)

In [ ]:
t = tf.constant([[1, 2], [3, 4]])
tf.shape(t).numpy()

array([2, 2], dtype=int32)

In [ ]:
t = tf.constant([
                 [
                  [
                   [1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]
                   ], 
                  [
                   [13, 14, 15, 16], 
                   [17, 18, 19, 20], 
                   [21, 22, 23, 24]
                   ]
                  ]
                 ])
tf.shape(t).numpy()

array([1, 2, 3, 4], dtype=int32)

In [ ]:
t = tf.constant([
                 [
                  [
                   [1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]
                   ], 
                  [
                   [13, 14, 15, 16], 
                   [17, 18, 19, 20], 
                   [21, 22, 23, 24]
                   ]
                  ]
                 ])

pp.pprint(t)

<tf.Tensor: shape=(1, 2, 3, 4), dtype=int32, numpy=
array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]], dtype=int32)>


In [4]:
# Matmul VS multiply 1

matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])

(matrix1 + matrix2).numpy()

array([[5., 5.]], dtype=float32)

In [5]:
# Matmul VS multiply 2
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])

print("Metrix 1 shape", matrix1.shape)
print("Metrix 2 shape", matrix2.shape)

tf.matmul(matrix1, matrix2).numpy()

Metrix 1 shape (2, 2)
Metrix 2 shape (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [6]:
# Matmul VS multiply 3

(matrix1*matrix2).numpy()

array([[1., 2.],
       [6., 8.]], dtype=float32)

In [7]:
# Broadcasting 1

matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])

(matrix1 + matrix2).numpy()

array([[5., 5.]], dtype=float32)

In [13]:
# BroadCasting 2

matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)

print(matrix1.numpy())      # numpy는 값만 나온다
print(matrix1)                
print(matrix2.numpy())

(matrix1 + matrix2).numpy()

[[1. 2.]]
tf.Tensor([[1. 2.]], shape=(1, 2), dtype=float32)
3.0


array([[4., 5.]], dtype=float32)

In [14]:
# BroadCasting 3

matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([3., 4.])

print(matrix1.numpy())
print(matrix2.numpy())

(matrix1 + matrix2).numpy()

[[1. 2.]]
[3. 4.]


array([[4., 6.]], dtype=float32)

In [15]:
# BroadCasting 4

matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.], [4.]])

print(matrix1.numpy())
print(matrix2.numpy())

(matrix1 + matrix2).numpy()

[[1. 2.]]
[[3.]
 [4.]]


array([[4., 5.],
       [5., 6.]], dtype=float32)

In [19]:
# Reduce mean 1

print(tf.reduce_mean([1, 2], axis=0).numpy())
tf.reduce_mean([1., 2.], axis=0).numpy()

1


1.5

In [17]:
# Reduce mean 2

x = [[1., 2.],
     [3., 4.]]

tf.reduce_mean(x).numpy()

2.5

In [25]:
# Reduce mean 3

pp.pprint(x)

tf.reduce_mean(x, axis=0).numpy()   # 세로 축으로 평균

[[1.0, 2.0], [3.0, 4.0]]


array([2., 3.], dtype=float32)

In [21]:
# reduce mean 4

pp.pprint(x)

tf.reduce_mean(x, axis=1).numpy()   # 가로 축으로 평균

array([1.5, 3.5], dtype=float32)

In [26]:
# reduce mean 5

pp.pprint(x)

tf.reduce_mean(x, axis=-1).numpy()

[[1.0, 2.0], [3.0, 4.0]]


array([1.5, 3.5], dtype=float32)

In [29]:
# reduce sum 1

pp.pprint(x)

tf.reduce_sum(x).numpy()    # 모든 원소의 합

[[1.0, 2.0], [3.0, 4.0]]


10.0

In [30]:
# reduce sum 2

pp.pprint(x)

tf.reduce_sum(x, axis = 0).numpy()    # 세로 축의 합

[[1.0, 2.0], [3.0, 4.0]]


array([4., 6.], dtype=float32)

In [31]:
# reduce sum 3

pp.pprint(x)

tf.reduce_sum(x, axis = -1).numpy()   # -1은 1과 같다. 결국은 가로 축의 합

[[1.0, 2.0], [3.0, 4.0]]


array([3., 7.], dtype=float32)

In [33]:
# reduce sum 4

pp.pprint(x)

print(tf.reduce_sum(x, axis=-1).numpy())

tf.reduce_mean(tf.reduce_sum(x, axis= -1)).numpy()

[[1.0, 2.0], [3.0, 4.0]]
[3. 7.]


5.0

In [35]:
# Argmax 1

x = [[0, 1, 2],
   [2, 1, 0]]

tf.argmax(x, axis=0).numpy()

array([1, 0, 0])

In [36]:
# Argmax 2

pp.pprint(x)

tf.argmax(x, axis=1).numpy()

[[0, 1, 2], [2, 1, 0]]


array([2, 0])

In [37]:
# Argmax 3

pp.pprint(x)

tf.argmax(x, axis=-1).numpy()

[[0, 1, 2], [2, 1, 0]]


array([2, 0])

In [40]:
# Reshape

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              
              [[6, 7, 8],
               [9, 10, 11]]])

print(t.shape)

tf.reshape(t, shape=[-1, 3]).numpy()    # -1 : 원래 있는 것(4행)에 맞춰서 알아서 조정해라..

(2, 2, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
# Reshape 2

tf.reshape(t, shape=[-1, 1, 3]).numpy()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [42]:
# Reshape (squeeze, expand)

tf.squeeze([[0], [1], [2]]).numpy()     # squeeze는 차원 중 사이즈가 1인 것을 찾아 스칼라 값으로 바꿔 해당 차원을 제거

array([0, 1, 2], dtype=int32)

In [43]:
# Reshape (squeeze, expand)

tf.expand_dims([0, 1, 2], 1).numpy() # axis로 지정된 차원을 추가 (2번째 인자값은 axis인듯?)

array([[0],
       [1],
       [2]], dtype=int32)

In [58]:
# One hot

x = np.array([[0], [1], [2], [0]])

print(x)
print(x.shape)

t = tf.one_hot(x, depth=3)  # one_hot으로 depth로 길이를 지정한 list에 x의 원소값들을 해당 리스트에 지정
t.numpy()

[[0]
 [1]
 [2]
 [0]]
(4, 1)


array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [50]:
# One hot 2

tf.one_hot(x, depth=2).numpy()      ## depth를 2로 사용하면 x 의 원소 값이 2인 위치는 출력 x

array([[[1., 0.]],

       [[0., 1.]],

       [[0., 0.]],

       [[1., 0.]]], dtype=float32)

In [55]:
# One hot 3

print(t)

tf.reshape(t, shape=[-1, 3]).numpy()

tf.Tensor(
[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[1. 0. 0.]]], shape=(4, 1, 3), dtype=float32)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [56]:
# One hot 4

tf.reshape(t, shape=[-1,2]).numpy()

array([[1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.]], dtype=float32)

In [57]:
# Casting 

tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).numpy()   ## 32비트 정수화

array([1, 2, 3, 4], dtype=int32)

In [62]:
# Casting 2

tf.cast([True, False, 1==1, 0==1], tf.int32).numpy()

array([1, 0, 1, 0], dtype=int32)

In [63]:
# Stack 

x = [1, 4]
y = [2, 5]
z = [3, 6]

tf.stack([x, y, z]).numpy()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [64]:
# Stack 2

tf.stack([x, y, z], axis = 1).numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [65]:
# Ones and Zeros like

x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).numpy()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [66]:
# Ones and Zeros like 2

tf.zeros_like(x).numpy()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [67]:
# Zip

for x, y in zip([1, 2, 3], [4, 5, 6]):
  print(x, y)

1 4
2 5
3 6


In [69]:
# Zip 2

for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
  print(x, y, z)

1 4 7
2 5 8
3 6 9
