In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__   # 버전 체크

'2.2.0'

In [ ]:
a = 10
b = 20
print(a+b)

30


In [ ]:
%tensorflow_version 1.x  # 버전 변경 / 이미 로드된 tensorflow 버전이 있으므로 
                        # 1.x 버전을 사용하고 싶으면 런타임을 다시 실행
                        # 2.0과 1.x 버전 사용법이 다르다

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `1.x  # 버전 변경 / 이미 로드된 tensorflow 버전이 있으므로`. This will be interpreted as: `1.x`.


TensorFlow 1.x selected.


In [ ]:
import tensorflow as tf
tf.__version__      # 런타임 재시작을 눌러서 버전을 변경한 후 버전 체크

'1.15.2'

In [ ]:
a = 10
b = 20
ts = tf.add(a, b)   # tensorflow를 사용하여 코딩
print(ts)           # 30이라는 것은 나오질 않는다.


Tensor("Add:0", shape=(), dtype=int32)


In [ ]:
a = 10
b = 20
ts = tf.add(a, b)   

sess = tf.Session()   # tensorflow는 session을 이용하여 연산을 사용해야만 한다.
print(sess.run(ts))
sess.close()          # 항상 close 해줘야 한다.

30


In [12]:
x = 2
y = 3
pow1 = tf.pow(x, 2)
mul1 = tf.multiply(pow1, y)
add1 = tf.add(y, 2)
add2 = tf.add(mul1, add1)

with tf.Session() as sess:    # 이 구문을 사용하면 close를 안해줘도 된다.
  print(sess.run(pow1))
  print(sess.run(add2))

4
17


In [11]:
x = 2
y = 3
add_op = tf.add(x, y, name='Add')
mul_op = tf.multiply(x, y, name='Multiply')
pow_op = tf.pow(add_op, mul_op, name='Power')
useless_op = tf.multiply(x, add_op, name='Useless')

with tf.Session() as sess:
  print(sess.run(pow_op))
  print(sess.run(useless_op))

15625
10


In [18]:
# 텐서플로 난수

r1 = tf.random_normal([1])
r2 = tf.random_normal([1])

print(r1)
print("===============")
print(r2)
print("===============")
with tf.Session() as sess:
  n1, n2 = sess.run([r1, r2])
  print(n1, n2)

Tensor("random_normal_10:0", shape=(1,), dtype=float32)
Tensor("random_normal_11:0", shape=(1,), dtype=float32)
[1.0512785] [-0.04422196]


In [20]:
# 텐서플로 난수 2

r1 = tf.random_normal([1, 3])   # 1행 3열 --> 즉 3개
r2 = tf.random_normal([1, 5])

print(r1)
print("==========")
print(r2)
print("==========")

with tf.Session() as sess:
  n1, n2 = sess.run([r1, r2])
  print(n1, n2)

Tensor("random_normal_14:0", shape=(1, 3), dtype=float32)
Tensor("random_normal_15:0", shape=(1, 5), dtype=float32)
[[-0.58848596  1.0563126   0.04225145]] [[ 1.8364217   0.28422293 -3.6531775   0.03004275 -1.9501146 ]]


In [21]:
# hello world 코딩  

hello = tf.constant('Hello World')
sess = tf.Session()

print(sess.run(hello))

sess.close()

b'Hello World'


In [22]:
# with 구문 example  

x = tf.constant(1.)
bool = tf.constant(True)
res = tf.cond(bool, lambda: tf.add(x, 1.), lambda: tf.add(x, 10.))

with tf.Session() as sess:
  print(sess.run(res))

2.0


In [24]:
# with 구문 example 2

a = tf.constant([5], dtype=tf.float32)
b = tf.constant([10], dtype=tf.float32)
c = tf.constant([2], dtype=tf.float32)

d = a * b + c

with tf.Session() as sess:
  print(sess.run(d))

[52.]


In [25]:
# with 구문 example 3

a = tf.constant(5, dtype=tf.float32)
# a = 5

with tf.Session() as sess:
  print(sess.run(a))

5.0


In [26]:
# 텐서를 세션 없이 실행 - 세션을 가지고 실행

x = tf.constant([1, 2, 3])
y = tf.constant([5, 6, 7])

with tf.Session() as sess:
  print(sess.run(x + y))

[ 6  8 10]


In [28]:
# 텐서를 세션 없이 실행 - 세션을 가지고 실행 2  

x = tf.constant([1, 2, 3])
y = tf.constant([[1], [2], [3]])

with tf.Session() as sess:
  print(sess.run(x + y))

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [30]:
# 텐서를 세션 없이 실행 - 세션을 가지지 않고 실행 
# 그대로 출력 (그래프의 정보를 출력)

a = 2
b = 3 
c = tf.add(a, b, name='Add')
print(c)

Tensor("Add_18:0", shape=(), dtype=int32)


In [31]:
# tf.reduce_mean example 

a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(5)

# Some more operation
mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

with tf.Session() as sess:
  print("mean = ", sess.run(mean))
  print("sum = ", sess.run(sum))

mean =  3
sum =  10


In [33]:
# 즉시 실행

tf.executing_eagerly()    # tensorflow 1.x 버전을 사용하고 있어서 False로 나온다. 즉, 즉시 실행이 기본이 아니다.

False

In [35]:
# 즉시 실행 예제

interactive_sess = tf.InteractiveSession()    # 1.x 버전은 즉시 실행을 이렇게 사용 (session 없이)
a = 2
b = 3
c = tf.add(a, b, name='Add')
print(c.eval())                               # 결과를 볼 때에는 메소드 eval() 사용

5


/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [36]:
# 즉시 실행 예제 2

x = tf.constant(1.)
bool = tf.constant(True)
res = tf.cond(bool, lambda: tf.add(x, 1.), lambda: tf.add(x, 10.))

print(res.eval())

2.0


In [1]:
# 텐서플로 2.0 버전으로 실행

try:

  %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf

tf.__version__                # Ctrl + M + . 키로 런타임 재시작 후 이 것부터 실행

'2.2.0'

In [2]:
tf.executing_eagerly()        # 즉시 실행 True

True

In [4]:
# 텐서플로 2.0 예제

hello = tf.constant('Hello World')
print(hello)
print(hello.numpy())              # 값 만 보려면 메소드 numpy() 사용

tf.Tensor(b'Hello World', shape=(), dtype=string)
b'Hello World'


In [6]:
# 텐서플로 2.0 예제 2

a = tf.constant(5)
b = tf.constant(3)
print(a + b)
print((a+b).numpy())

tf.Tensor(8, shape=(), dtype=int32)
8


In [9]:
# 텐서플로 2.0 예제 3

c = tf.constant('Hello, World!')

with tf.Session() as sess:
  print(sess.run(c))          # 버전이 1.x이 아닌 2.x이므로 에러 발생 --> 2.x은 session 사용 x

AttributeError: ignored