In [1]:
# 코드 환경 셋팅

import tensorflow as tf
import numpy as np
import pprint           # print를 조금 더 이쁘게 나오도록 하는 라이브러리

pp = pprint.PrettyPrinter(indent=4)
print(tf.__version__)

2.2.0


In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)

print(t.ndim)
print(t.shape)
print(t[0], t[1], t[-1])
print(t[2:5], t[4: -1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [3]:
t = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
pp.pprint(t)

print(t.ndim)
print(t.shape)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])
2
(4, 3)


In [4]:
t = tf.constant([1, 2, 3, 4])
tf.shape(t).eval()                # eval()은 tensorflow 1.x 버전대의 메소드 / 2.x 버전은 numpy()

NotImplementedError: ignored

In [5]:
t = tf.constant([1, 2, 3, 4])
tf.shape(t).numpy()

array([4], dtype=int32)

In [6]:
t = tf.constant([[1, 2], [3, 4]])
tf.shape(t).numpy()

array([2, 2], dtype=int32)

In [10]:
t = tf.constant([
                 [
                  [
                   [1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]
                   ], 
                  [
                   [13, 14, 15, 16], 
                   [17, 18, 19, 20], 
                   [21, 22, 23, 24]
                   ]
                  ]
                 ])
tf.shape(t).numpy()

array([1, 2, 3, 4], dtype=int32)

In [11]:
t = tf.constant([
                 [
                  [
                   [1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]
                   ], 
                  [
                   [13, 14, 15, 16], 
                   [17, 18, 19, 20], 
                   [21, 22, 23, 24]
                   ]
                  ]
                 ])

pp.pprint(t)

<tf.Tensor: shape=(1, 2, 3, 4), dtype=int32, numpy=
array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]], dtype=int32)>
